* Short
This is the story of the little blue boat. The boat has 1 Motor1 Servo and controlled over bluethooth by dabble. The boat is made of foam.

* The Blue boat
The discribtion of the follow site is used to make the boat.

https://www.rcpano.net/2020/08/20/how-to-make-fast-rc-boat-diy-basic-single-motor-rc-boat/


* GIT  
repository https://github.com/gedonder/blueboat
Here the comments for project registration which i always forget.


#+begin_src 
git add .
git commit -m "commit"
git remote add origin git@github.com:gedonder/blueboat.git
git push -u origin main

#+end_src

* Software
** Arduino
*** Wokwi
Ontwikkel de software op Wokwi
https://wokwi.com/dashboard/projects

*** Motor draaien 
*** Servo draaien
**** stap 1 dd`
Servo gaat naar 45 of -45
2 funties turnLeft en turnRight

*** Dabble control -> Print motor aan , motor uit, servo val
 
** Dabble
The dabble library is  available on wokwi. But i was not able to use this propperly. 
Dabble.ino is a test file to test the functions to gether with the the dabble app in the gamepad screen. There are multiple modes in the gamepad
 
Steps:
1. connect esp to the laptop
1. arduino settings XIAO_ESP32 on /dev/cu.usbmodem14101
1. press the boot button on the esp or remove usb cable, press boot button, insert usb cable 
1. Run the software and upload
1. Press reset button on esp
1. On iphone in the dabble app connect to the esp
1. In arduino open serial monitor. Tools

Problems:
- exit status 2  -> remove usb cable, press boot button, insert usb cable 

* Hardware
** ESP32-C3
https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started/

*** Gebruik
boot pin : voor het uploaden van software
*** Declaren van een pin
const int led = D10;



* Linkjes

https://github.com/gedonder/blueboat
